### ISSUE TITLE
Normal for white light should be a single line centered within the distribution

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#51] opened 2015-06-01 16:04 UTC
Steps to reproduce

1) open sim
2) open prisms
3) drag a few prisms into the light boundaries; try to transmit as much light as possible through the prisms
4) turn on normal and reflected
5) turn on white light

Here is a picture of the sim without white light

![bendinglightscreenshot1](https://cloud.githubusercontent.com/assets/7717368/7917116/29022922-0845-11e5-9c65-922a135b1868.png)

Here is a picture of the same sim with white light

![bendinglightscreenshot2](https://cloud.githubusercontent.com/assets/7717368/7917140/563c5ab6-0845-11e5-8916-b30581acdad0.png)

**Comment by arnabp** [comment] 2015-06-01 21:30
My understanding of this was that there is a normal line for each color of light that's split, so the normal lines multiply and the effect is intentional, right?

**Comment by arouinfar** [comment] 2015-06-02 20:07
@arnabp is correct, though I don't find the thicker lines to be all that useful. Without being able to zoom in, it is impossible to resolve groups of normal lines.
![image](https://cloud.githubusercontent.com/assets/8419308/7945557/c6615d84-092e-11e5-98dc-6c79215bebb5.png)

@bryo5363's screenshots also demonstrate #63. The white light does not propagate beyond the dev boundaries, but monochromatic light does.

**Comment by arouinfar** [comment] 2015-06-02 23:48
This issue should be brought to the design team for discussion. There are a few options:
- Keep the normal lines as they are now
- A single normal line that falls in the middle of the distribution
- A single normal line for a single color at the edge of the distribution (i.e. red or violet)

Self-assigning for now.

**Comment by arouinfar** [comment] 2015-08-10 22:04
After discussing with @ariel-phet, we've decided that a single normal line that falls within the center of the dispersion is the best option. Assigning to @samreid to implement.

**Comment by samreid** [comment] 2015-08-21 16:32
To implement this, we will need to track each "bundle" of rays that go together and only add one renderable intersection object for the bundle.

**Comment by samreid** [comment] 2015-08-21 16:52
A shortcut might be just to show intersections for selected wavelengths in the white light bundle.  Performing a nonlinear interpolation nearest to the centroid of a bundle of intersections would be very complicated and take much more time to get it right.  Just showing for selected wavelengths in the white light bundle should be very easy to try.  @ariel-phet OK with you if I try this first?

**Comment by samreid** [comment] 2015-08-21 16:54
The primary possibilities would be (a) showing a single line for the median wavelength or (b) showing 2 lines, one for the max wavelength and one for the min wavelength.  Note that if the bundle of rays gets separated, the lines would just appear for the selected rays.

**Comment by ariel-phet** [comment] 2015-08-24 21:38
Going to try showing normal just for min and max wavelength

**Comment by samreid** [comment] 2015-08-25 03:25
To clarify, this is for the max and min wavelengths for the original bundle of rays, not for each subdivision of rays.  This means when a white beam gets separated, the normal will remain with the red/violet.

**Comment by samreid** [comment] 2015-08-25 19:54
Implemented in http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.17/bending-light_en.html @ariel-phet please review the behavior and let me know your thoughts.

**Comment by ariel-phet** [comment] 2015-08-28 15:51
I think this is an improvement...we might decide to do these normals in the min and max colors to make it a bit clearer why we have two, but closing this issue.

**Comment by samreid** [comment] 2015-08-28 15:59
> we might decide to do these normals in the min and max colors to make it a bit clearer why we have two

I'm confused.  The normals are already located at the min and max wavelengths, so I'm not sure what you mean here:

![image](https://cloud.githubusercontent.com/assets/679486/9550915/5b50af50-4d6b-11e5-9d14-289dde508773.png)

Perhaps the issue is that the each ray has a stroke of more than a few pixels and the normal is centered on the middle of the ray?

**Comment by ariel-phet** [comment] 2015-08-28 16:03
@samreid notice I said "in the min and max colors" -- to clarify, I meant perhaps having the normal for red by colored red, and the normal for violet be colored violet (instead of black). I do not thing that will be necessary, and we will just explain in the teacher tips/sim primer. It was just a thought for the future.

**Closed by ariel-phet** 2015-08-28 16:03 UTC
Labels: design, prisms-screen
