### ISSUE TITLE
CT Fatal error: tsc failed with code: 1

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bending-light#406] opened 2022-03-30 15:16 UTC
```
bending-light : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Fatal error: tsc failed with code: 1
stdout:
js/common/view/WavelengthControl.ts(43,74): error TS2345: Argument of type '{ cursorStroke: string; maxWavelength: number; thumbWidth: number; thumbHeight: number; trackWidth: number; trackHeight: number; tweakersVisible: false; valueVisible: false; thumbTouchAreaYDilation: number; }' is not assignable to parameter of type 'WavelengthSliderOptions'.
Type '{ cursorStroke: string; maxWavelength: number; thumbWidth: number; thumbHeight: number; trackWidth: number; trackHeight: number; tweakersVisible: false; valueVisible: false; thumbTouchAreaYDilation: number; }' is missing the following properties from type 'Omit<SpectrumSliderOptions, "minValue" | "maxValue">': valueProperty, enabledRangeProperty

2 problems found.

stderr:

Snapshot from 3/29/2022, 10:41:48 PM
```

**Comment by samreid** [comment] 2022-03-30 20:31
Likely duplicate of https://github.com/phetsims/bending-light/issues/405, closing.

**Closed by samreid** 2022-03-30 20:31 UTC
Labels: type:automated-testing
