### ISSUE TITLE
Glass Glass interface shows reflected angle

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/bending-light#288] opened 2015-11-03 03:20 UTC
On the more tools screen if you turn the angle display on, and set both materials to glass using the combo box, you get a displayed reflected angle, but no reflected beam (there should not be a reflected beam so that is correct). We might need some logic to remove the reflected angle.

![glass-glass](https://cloud.githubusercontent.com/assets/4051174/10900586/2e2deb9c-819f-11e5-8bd9-026efebc122d.PNG)

**Comment by arouinfar** [comment] 2015-11-03 06:03
This bug happens at any boundary where n1=n2, not just glass/glass.

**Comment by samreid** [comment] 2015-11-06 02:39
Fixed above, but revealed a corner case where the angle jumps.  The issue is when n1=n2 and the angle goes from 89.9 degrees to 90.0 degrees, the amount transmitted goes from 100% to 0%, so the angle readout has a discontinuity here.  Note that for total internal reflection, there is no discontinuity, since the reflected remains at 100% in either case.

I'll try to capture it in a screencast:

![out](https://cloud.githubusercontent.com/assets/679486/10987908/cf7de93c-83f4-11e5-94dd-cfeda957c64e.gif)

@arouinfar @ariel-phet do you want to do something about this discontinuity?  If so, what?  Let me know if you need a version you can test yourself.

**Comment by ariel-phet** [comment] 2015-11-06 16:06
I think it would be fine to leave as is...but if it is easy to change, I mean technically there is not really a "reflected" ray there is only an "incident" ray. So I would think in all cases where the angle is 90 degrees you could just show the incident angle (regardless of n1 or n2) since then you are just going along the boundary and measuring a "refelected" ray doesn't really make sense.

**Comment by arouinfar** [comment] 2015-11-06 16:37
@samreid I also think it would be fine to leave as is, but @ariel-phet's suggestion is a good solution if easy to implement.

**Comment by samreid** [comment] 2015-11-06 18:26
Fixed as described in the comment above and published here for testing:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.40/bending-light_en.html

@ariel-phet and @arouinfar can you review?  If this seems good, we are ready for dev testing.

**Comment by arouinfar** [comment] 2015-11-06 18:32
Looks great @samreid!

**Comment by samreid** [comment] 2015-11-06 18:33
Thanks, I'll close this one and create a new issue for dev testing.

**Closed by samreid** 2015-11-06 18:33 UTC
Labels: bug
