### ISSUE TITLE
Tools should be layered above panels

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#66] opened 2015-06-03 15:52 UTC
On the Intro and More Tools screens, the intensity meter and protractor should be layered above the panels like the speed and wave detector tools. They can currently go behind the panels:
![image](https://cloud.githubusercontent.com/assets/8419308/7964614/e4fe4868-09d5-11e5-848b-dae62dc5c18a.png)

**Comment by bryo5363** [comment] 2015-06-03 19:02
Tools are also layered underneath the wave

![screen shot 2015-06-03 at 1 00 59 pm](https://cloud.githubusercontent.com/assets/7717368/7968912/d09e43bc-09f0-11e5-8b48-a41d423458ba.png)

**Comment by arouinfar** [comment] 2015-06-03 19:19
It looks like only the Intensity meter is layered beneath the wave. This probe should remain behind the  wave, but the body of the tool would be more visible above the wave. If the probe and body can live is different layers, it would be best to move the <i>body</i> of the intensity meter on top of the wave.

**Comment by ChandrashekarBemagoni** [comment] 2015-06-04 14:11
Present tools layering order is  matching java version.

**Comment by arouinfar** [comment] 2015-06-04 17:06
I've confirmed that the layering matches the Java version, @ChandrashekarBemagoni. 

I've also found that the intensity meter is layered behind the normal. All other meters are layered on top of the normal.
![image](https://cloud.githubusercontent.com/assets/8419308/7989820/739dd7ae-0aa9-11e5-9efe-92c1032b7436.png)
 
@ariel-phet, I think we should address the layering before release.

**Comment by samreid** [comment] 2015-08-08 22:26
@arouinfar I have this comment from the bending light Java code:

```java
    // In order to make controls (including the laser itself) accessible (not obscured by the large protractor), KP
    // suggested this layering order:
    // laser in front
    // Control boxes next
    // Protractor and other tools
    // Laser beam in the back
```

Can you please review Kathy's suggestion and provide a complete list of what you recommend for the HTML version?

**Comment by samreid** [comment] 2015-08-08 22:35
When providing a list of the rendering order (the z-order), please also include prisms, see #71

**Comment by samreid** [comment] 2015-08-08 22:42
Oh, I guess it would be weird if prisms went in front of control panels but light went behind control panels.  But we should still include prisms in the z-ordering list.

**Comment by samreid** [comment] 2015-08-21 15:39
Is this a duplicate of #178 ?

**Comment by samreid** [comment] 2015-08-21 15:40
Reassigned to @ariel-phet to see if there is anything else to do here, or if it is all covered in #178.

**Comment by ariel-phet** [comment] 2015-08-24 21:32
Temporal sensor behind control panels
All sensors should go in front of play/pause slow mo
"Bump out" rule if behind a control panel

**Comment by samreid** [comment] 2015-09-01 21:22
It looks like the protractor on screen 2 should also go behind the control panels (to match the rest of the sim).  Somebody correct me if I'm wrong!

**Comment by samreid** [comment] 2015-09-01 21:25
I'm going to create sub-issues for the remaining work.  In this issue, I moved the material control panels to the front and the play/pause slow mo to the back.  We still need the "bump out" rule if a sensor is dropped behind a control panel and putting the prisms protractor behind the control panels.

**Comment by samreid** [comment] 2015-09-01 21:28
I created sub-issues for the remaining work and will close this one.

**Closed by samreid** 2015-09-01 21:28 UTC
