### ISSUE TITLE
Dragging index sliders has different min/max values than clicking the index arrows

### ISSUE THREAD

**Issue by phet-steele** [phetsims/bending-light#57] opened 2015-06-01 17:35 UTC
Currently on the More Tools screen, I can drag the sliders for the index of refraction to farther mins and maxes than I can by just clicking the right and left arrows.

Sliding I reach 1.000 and 1.606:
![slide values](https://cloud.githubusercontent.com/assets/5863899/7918813/5eb2412c-0851-11e5-8357-b11ff03136a5.PNG)

Clicking I reach 1.005 and 1.602
![click values](https://cloud.githubusercontent.com/assets/5863899/7918847/9ac5cb7a-0851-11e5-8083-4b75b34ca213.PNG)

Tested on Win 8.1 FF

Troubleshooting information:
Name: Bending Light
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.3/bending-light_en.html
Version: 1.0.0-dev.3 2015-05-31 01:07:46 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"comment":"# bending-light 1.0.0-dev.3 Sat May 30 2015 19:07:45 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"4875945b5eb9027d4994f6ffa990b664979c1d86","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"bending-light":{"sha":"e99296da4f6ca1fff8fc142e89c34f7352c87eb4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"60c6645455a0692ec65c701c462399822599b1ef","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"ee8f44af90bd8dfd7d13399ecb429348c94e8dd5","branch":"master"}}

**Comment by arouinfar** [comment] 2015-06-03 00:03
At first I was unable to reproduce this issue, because I had the wavelength at the default of 650nm. If I set the value of n to 1.600 and then reduce the wavelength to 380 nm, the index of refraction will become 1.622. This behavior exists because the index of refraction of depends on the wavelength (inversely related). The Java sim also behaves similarly.

**Comment by ChandrashekarBemagoni** [comment] 2015-06-03 13:24
Fixed in above commit. Assigning to @phet-steele for verification

**Comment by arouinfar** [comment] 2015-06-03 19:58
@phet-steele and I confirmed that the issue has been fixed. Closing.

**Closed by arouinfar** 2015-06-03 19:58 UTC
