### ISSUE TITLE
CT Bounds mismatch after validateBounds

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bending-light#396] opened 2020-12-02 16:23 UTC
```
bending-light : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1606867678068%22%2C%22timestamp%22%3A1606882690164%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1369:23
at ShadedRectangle.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1374:10)
at Node.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1218:29)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/axon/js/TinyProperty.js:52:17)
at Node.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1784:32)
at Node.getRightBottom (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:3131:17)
at Node.get rightBottom [as rightBottom] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:3133:35)
at new NodeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/util/NodeProperty.js:25:16)
id: Bayes Chrome
Snapshot from 12/1/2020, 5:07:58 PM

----------------------------------

bending-light : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1606867678068%22%2C%22timestamp%22%3A1606898506453%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1369:23
at ShadedRectangle.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1374:10)
at Node.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1218:29)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/axon/js/TinyProperty.js:52:17)
at Node.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1784:32)
at Node.getRightBottom (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:3131:17)
at Node.get rightBottom [as rightBottom] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:3133:35)
at new NodeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/util/NodeProperty.js:25:16)
id: Bayes Chrome
Snapshot from 12/1/2020, 5:07:58 PM

----------------------------------

bending-light : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1606867678068%22%2C%22timestamp%22%3A1606914135332%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1369:23
at ShadedRectangle.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1374:10)
at Node.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1218:29)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/axon/js/TinyProperty.js:52:17)
at Node.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:1784:32)
at Node.getRightBottom (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:3131:17)
at Node.get rightBottom [as rightBottom] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/nodes/Node.js:3133:35)
at new NodeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606867678068/scenery/js/util/NodeProperty.js:25:16)
id: Bayes Chrome
Snapshot from 12/1/2020, 5:07:58 PM
```

**Comment by samreid** [comment] 2020-12-02 19:49
This looks similar to https://github.com/phetsims/joist/issues/656

**Comment by KatieWoe** [comment] 2020-12-04 16:26
Looks like it might have gone away, but then came back:
```
bending-light : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1607071519170%22%2C%22timestamp%22%3A1607081062104%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/scenery/js/nodes/Node.js:1369:23
at ShadedRectangle.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/scenery/js/nodes/Node.js:1374:10)
at Node.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/scenery/js/nodes/Node.js:1218:29)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/axon/js/TinyProperty.js:52:17)
at Node.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/scenery/js/nodes/Node.js:1784:32)
at Node.getRightBottom (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/scenery/js/nodes/Node.js:3131:17)
at Node.get rightBottom [as rightBottom] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/scenery/js/nodes/Node.js:3133:35)
at new NodeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607071519170/scenery/js/util/NodeProperty.js:25:16)
id: Bayes Chrome
Snapshot from 12/4/2020, 1:45:19 AM
```

**Comment by KatieWoe** [comment] 2020-12-08 16:22
```
bending-light : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1607422608277%22%2C%22timestamp%22%3A1607435102996%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/scenery/js/nodes/Node.js:1369:23
at ShadedRectangle.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/scenery/js/nodes/Node.js:1374:10)
at Node.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/scenery/js/nodes/Node.js:1218:29)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/axon/js/TinyProperty.js:52:17)
at Node.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/scenery/js/nodes/Node.js:1784:32)
at Node.getRightBottom (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/scenery/js/nodes/Node.js:3131:17)
at Node.get rightBottom [as rightBottom] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/scenery/js/nodes/Node.js:3133:35)
at new NodeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607422608277/scenery/js/util/NodeProperty.js:25:16)
id: Bayes Chrome
Snapshot from 12/8/2020, 3:16:48 AM
```

**Comment by KatieWoe** [comment] 2020-12-14 16:19
Showing up again more consistently.
```
bending-light : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1607895437240%22%2C%22timestamp%22%3A1607908910290%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1369:23
at ShadedRectangle.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1374:10)
at Node.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1218:29)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/axon/js/TinyProperty.js:52:17)
at Node.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1784:32)
at Node.getRightBottom (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:3131:17)
at Node.get rightBottom [as rightBottom] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:3133:35)
at new NodeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/util/NodeProperty.js:25:16)
id: Bayes Chrome
Snapshot from 12/13/2020, 2:37:17 PM

----------------------------------

bending-light : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1607895437240%22%2C%22timestamp%22%3A1607923926218%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1369:23
at ShadedRectangle.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1374:10)
at Node.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1218:29)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/axon/js/TinyProperty.js:52:17)
at Node.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1784:32)
at Node.getRightBottom (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:3131:17)
at Node.get rightBottom [as rightBottom] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:3133:35)
at new NodeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/util/NodeProperty.js:25:16)
id: Bayes Chrome
Snapshot from 12/13/2020, 2:37:17 PM

----------------------------------

bending-light : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1607895437240%22%2C%22timestamp%22%3A1607939499745%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1369:23
at ShadedRectangle.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1374:10)
at Node.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1218:29)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/axon/js/TinyProperty.js:52:17)
at Node.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1784:32)
at Node.getRightBottom (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:3131:17)
at Node.get rightBottom [as rightBottom] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:3133:35)
at new NodeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/util/NodeProperty.js:25:16)
id: Bayes Chrome
Snapshot from 12/13/2020, 2:37:17 PM

----------------------------------

bending-light : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/bending-light/bending-light_en.html?continuousTest=%7B%22test%22%3A%5B%22bending-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1607895437240%22%2C%22timestamp%22%3A1607955442494%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(8.849999999999994,126.15),y:(11,69)], expected: [x:(5.849999999999994,129.15),y:(8,72)]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1369:23
at ShadedRectangle.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1374:10)
at Node.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1218:29)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/axon/js/TinyProperty.js:52:17)
at Node.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:1784:32)
at Node.getRightBottom (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:3131:17)
at Node.get rightBottom [as rightBottom] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/nodes/Node.js:3133:35)
at new NodeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607895437240/scenery/js/util/NodeProperty.js:25:16)
id: Bayes Chrome
Snapshot from 12/13/2020, 2:37:17 PM
```

**Comment by samreid** [comment] 2020-12-28 17:54
This issue is puzzling.  If I omit the titleNode and the chartNode from the bodyNode, then the problem is not triggered:

```diff
Index: js/more-tools/view/WaveSensorNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/more-tools/view/WaveSensorNode.js b/js/more-tools/view/WaveSensorNode.js
--- a/js/more-tools/view/WaveSensorNode.js	(revision d2b7db91dba026073989a43c2d3f5a99f13a66a9)
+++ b/js/more-tools/view/WaveSensorNode.js	(date 1609177938217)
@@ -131,7 +131,7 @@
     if ( titleNode.width > rectangleWidth - 15 ) {
       titleNode.scale( ( rectangleWidth - 15 ) / titleNode.width );
     }
-    this.bodyNode.addChild( titleNode );
+    // this.bodyNode.addChild( titleNode );
     titleNode.centerX = outerRectangle.centerX;
     const fractionalVerticalDistanceToTitle = 0.82;
     titleNode.y = this.bodyNode.height * fractionalVerticalDistanceToTitle;
@@ -141,7 +141,7 @@
       new Series( waveSensor.probe1.seriesProperty, darkProbeColor ),
       new Series( waveSensor.probe2.seriesProperty, lightProbeColor )
     ] );
-    this.bodyNode.addChild( this.chartNode );
+    // this.bodyNode.addChild( this.chartNode );
 
     // Create the probes
     this.probe1Node = new ProbeNodeWrapper( waveSensor.probe1, '#5c5d5f', modelViewTransform ); // @public (read-only)
```

However, both the title and chartNode appear to have legal, numeric bounds.  @jonathanolson can you please advise?

**Comment by jonathanolson** [comment] 2021-01-04 18:23
@samreid I recall this happening in `?eall` when client code directly mutated the relevant bounds. I'll do a brief check.

**Comment by jonathanolson** [comment] 2021-01-04 18:24
> innerMostRectangle.bounds.erode( 3 )

Presumably changing this to eroded should work, I'll test.

**Comment by jonathanolson** [comment] 2021-01-04 18:26
Verified it seems to fix the above issue. @samreid can you verify? Should we update the assertion message to better hint for that, now that we're running `?eall` more?

**Comment by samreid** [comment] 2021-01-04 18:31
That fix looks great, thanks! A better assertion message would be helpful, would you like a side issue for that?

**Comment by jonathanolson** [comment] 2021-01-04 18:40
Handled above, does that look good? (Don't feel like a side issue is needed, unless additional changes should be made).

**Comment by samreid** [comment] 2021-01-04 20:39
Excellent, thanks!  Closing.

**Closed by samreid** 2021-01-04 20:39 UTC
Labels: type:automated-testing
