### ISSUE TITLE
Wave view causes time graph to slow down

### ISSUE THREAD

**Issue by arnabp** [phetsims/bending-light#59] opened 2015-06-01 21:52 UTC
When measuring the light using the "Time" tool, the graph is much faster when selecting a ray than when selecting a wave, even though the two light types are the same and the speed tool does not indicate any change in speed.

Troubleshooting information (do not edit):
Name: Bending Light
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.3/bending-light_en.html
Version: 1.0.0-dev.3 2015-05-31 01:07:46 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.7 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.7
Language: en-us
Window: 1268x991
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.31)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"comment":"# bending-light 1.0.0-dev.3 Sat May 30 2015 19:07:45 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"4875945b5eb9027d4994f6ffa990b664979c1d86","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"bending-light":{"sha":"e99296da4f6ca1fff8fc142e89c34f7352c87eb4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"60c6645455a0692ec65c701c462399822599b1ef","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"ee8f44af90bd8dfd7d13399ecb429348c94e8dd5","branch":"master"}}

**Comment by elisemorgan** [comment] 2015-06-08 21:13
I also noticed this issue on an iPad2 with iOS 8.3

**Comment by samreid** [comment] 2015-08-08 22:20
I cannot reproduce this problem on my Macbook air using chrome and dev.3 as above.  But I do see the problem on iPad3--looks like it is related to the processing time of the wave mode (despite it being WebGL).

**Comment by samreid** [comment] 2015-08-19 23:21
This problem no longer occurs on the iPad3.  I do see a brief transient burst when changing from ray->wave, but it doesn't seem significant to me.  @arnabp can you test on your platform and report back?

http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.11/bending-light_en.html

**Comment by samreid** [comment] 2015-10-20 22:10
Since I can no longer reproduce the problem, it is probably solved.  Closing.

**Closed by samreid** 2015-10-20 22:10 UTC
