### ISSUE TITLE
Everything in Objects panel can be dragged out of bounds

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/bending-light#309] opened 2015-11-21 04:14 UTC
Test device: iPad2, Witten

Operating System: iOS 9.1 (13B143)

Browser: safari

Problem description: It is possible to drag all the stuff in the Objects panel out of the bounds. 

Steps to reproduce: Go to prisms screen. It is possible to move the right most shape (crescent) to by the protractor. Put finger on the knob of shape, but don't press down to trigger selection. Swipe finger quickly across the screen to the right. You can repeat this on all of the shapes. If you drag diagonally to the top right-hand corner, you will drag up everything in the panel. It is also possible to drag shapes out of the screen and lose them. 

Severity:

Screenshots:
![image 1](https://cloud.githubusercontent.com/assets/12610678/11316611/8c997ae0-8fcb-11e5-8464-ed78fa1fdaff.png)

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.45/bending-light_en.html
Version: 1.0.0-dev.45 2015-11-20 05:48:24 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"e67f1f6a","branch":"master"},"bending-light":{"sha":"51676950","branch":"master"},"brand":{"sha":"c9282935","branch":"master"},"chipper":{"sha":"a4994516","branch":"master"},"dot":{"sha":"5c39b7d8","branch":"master"},"joist":{"sha":"446cc8e8","branch":"master"},"kite":{"sha":"84e84bca","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"d9d2e688","branch":"master"},"scenery":{"sha":"a4a93afb","branch":"master"},"scenery-phet":{"sha":"5a6969fe","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"7b4a98d6","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"}}

**Comment by samreid** [comment] 2015-12-04 04:54
This is the closest I can get by doing various presses and drags on the prisms in the toolbox:

![image](https://cloud.githubusercontent.com/assets/679486/11582155/27b8802a-9a08-11e5-94aa-b263b0afb55d.png)

Can't reliably reproduce this and am not clear on this part of these instructions:

> Put finger on the knob of shape, but don't press down to trigger selection.

**Comment by samreid** [comment] 2015-12-04 04:58
@elisemorgan @ariel-phet @arouinfar I am having trouble reproducing this problem.  I was able to create a similar (though not identical) situation once or twice where the prism icon goes to the wrong part of the toolbox (like in the comment above).  Seems probably related.  But I don't think I can work on this too much until I can reliably reproduce the problem.  Any help would be great!

**Comment by ariel-phet** [comment] 2015-12-04 17:49
I think what @elisemorgan was suggesting to reproduce is hold finger near the knob (but not touching), then swipe quickly across.

**Comment by ariel-phet** [comment] 2015-12-04 17:50
Assigning to @arouinfar to see if she can reproduce...would be good to understand if we think this would happen in a normal use case, or do you really have to be trying to cause the issue.

**Comment by arouinfar** [comment] 2015-12-04 18:01
@samreid @ariel-phet I was able to reproduce this issue using @elisemorgan's procedure rather easily on iPad2/Whitten. It's a bit hard to describe, so I'm going to grab the iPad Air to do a quick screen recording.

**Comment by arouinfar** [comment] 2015-12-04 18:03
One thing worth noting is that the sim requires a hard refresh to return to normal. Reset all does not work.

**Comment by arouinfar** [comment] 2015-12-04 20:35
@samreid Here's a link to an annotated screen recording on the iPad Air:
https://drive.google.com/file/d/0B-YvjkIIcS_aajB4bmZJckx6RW8/view?usp=sharing

It's pretty easy to move the prism icons to the other side of the panel by hovering your finger over the exact location of the rotate knob and then quickly swiping to the right. 
![bendinglight309-2](https://cloud.githubusercontent.com/assets/8419308/11600025/5b787486-9a87-11e5-9376-720b296230df.gif)

Once a prism is moved to the right, it's easy to encounter buggy behavior.
![bendinglight309-3](https://cloud.githubusercontent.com/assets/8419308/11600570/c7a3e250-9a8a-11e5-84d4-afc0a2534d7d.gif)

To initially move a prism requires some atypical usage, but it's pretty easy to do. It wouldn't be hard to imagine a few students doing this accidentally. Once a prism is misplaced, several strange things can happen. The only way to return the sim to its normal state is through a browser refresh. I think it'd be worthwhile to investigate this issue a little further.

**Comment by samreid** [comment] 2015-12-08 06:12
@arouinfar with your description + screen captures I was able to recreate this problem on my 1st try, thanks!

**Comment by samreid** [comment] 2015-12-08 06:26
Proposed fix is above, and works well for me on iPad3.  I'd like @arouinfar and @elisemorgan to verify the change, but I want to fix #322 and do a bit of developer testing before publishing the next version.  Leaving assigned to me until then.

**Comment by samreid** [comment] 2015-12-08 07:03
@arouinfar and @elisemorgan could you please verify my change in this version?
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.46/bending-light_en.html

Please do not fully test the entire simulation--just enough to understand if this issue #309 is still in play.

**Comment by elisemorgan** [comment] 2015-12-08 15:20
@samreid The issue appears to be fixed. After swiping right for 5 minutes I was unable to recreate the behavior. @arouinfar please confirm

**Comment by arouinfar** [comment] 2015-12-08 19:22
Looks great @samreid! I was also unable to reproduce the behavior, so I'll go ahead and close this issue.

And by the way, nice catch @elisemorgan.

**Closed by arouinfar** 2015-12-08 19:22 UTC
Labels: bug
