### ISSUE TITLE
Moving Ray can break speed tool's icon

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/bending-light#327] opened 2015-12-11 17:52 UTC
Test device: iPad2, Tycho

Operating System: iOS 9.2 (13C75)

Browser: Safari

Problem description: If the light Ray is moving back and forth across the speed tool, it can cause parts of the tool icon to be cut out/broken. See screenshots

Steps to reproduce: Place speed tool on light Ray. Move light Ray away from speed tool, then back again, by adjusting the index of refraction. Observe gaps appearing in the icon of the speed tool.

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/12610678/11751181/290a017c-9ff5-11e5-89ad-892b9d085e99.png)
![image](https://cloud.githubusercontent.com/assets/12610678/11751182/291c7f78-9ff5-11e5-8c72-0383f0b166d4.png)

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.51/bending-light_en.html
Version: 1.0.0-dev.51 2015-12-10 22:05:11 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13C75 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"60075be9","branch":"master"},"babel":{"sha":"469a6f46","branch":"master"},"bending-light":{"sha":"007d4f70","branch":"master"},"brand":{"sha":"c9282935","branch":"master"},"chipper":{"sha":"d18a2538","branch":"master"},"dot":{"sha":"24f07fa0","branch":"master"},"joist":{"sha":"f73eef15","branch":"master"},"kite":{"sha":"a4907ccc","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"d712ace0","branch":"master"},"scenery":{"sha":"98ea2eeb","branch":"master"},"scenery-phet":{"sha":"a62aafce","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"1b39dfc5","branch":"master"},"tandem":{"sha":"87f3d2ab","branch":"master"}}

**Comment by samreid** [comment] 2015-12-11 19:19
Tagging @jonathanolson because he might be interested in this problem.

Following the directions above, I was not able to see this problem on iPad3 running iOS 9.2 (13C75)
![move320](https://cloud.githubusercontent.com/assets/679486/11753196/1134b108-a001-11e5-9e97-dff0f6899028.gif)

@elisemorgan can you try restarting Safari (double tap the home button, then swipe it away), and restart the iPad2 and see if the problem persists?  If the problem persists after restarting safari and restarting the ipad, please launch with ?screens=3 and see if the problem is present (this could point to a memory/context problem if the problem disappears with ?screens=3)

**Comment by elisemorgan** [comment] 2015-12-11 21:02
@samreid After refresh, I am no longer able to reproduce this issue. Bummer!

**Comment by samreid** [comment] 2015-12-17 19:00
Not reproducible, closing.

**Closed by samreid** 2015-12-17 19:00 UTC
Labels: bug
