### ISSUE TITLE
Laser does not gracefully return to dev when browser resized

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/bending-light#308] opened 2015-11-20 21:46 UTC
Test device: Schrodinger

Operating System: Win 8

Browser: Chrome

Problem description: In the prisms section of the sim, the laser pointer and the prisms can be moved outside the red box that appears with ?dev at the end of the url. (They can't actually be dragged off screen, just to the edge of the window.

Steps to reproduce: Make the window size such that there is a gap on the sides between the edge of the window and the red dev box, (a short but wide window will do this), and then drag the pointer and prisms off to the side.

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/11947677/11312739/624d4c34-8f95-11e5-8c0b-70dcc43e02ba.png)

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.45/bending-light_en.html?dev
Version: 1.0.0-dev.45 2015-11-20 05:48:24 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Language: en-US
Window: 1920x971
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"e67f1f6a","branch":"master"},"bending-light":{"sha":"51676950","branch":"master"},"brand":{"sha":"c9282935","branch":"master"},"chipper":{"sha":"a4994516","branch":"master"},"dot":{"sha":"5c39b7d8","branch":"master"},"joist":{"sha":"446cc8e8","branch":"master"},"kite":{"sha":"84e84bca","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"d9d2e688","branch":"master"},"scenery":{"sha":"a4a93afb","branch":"master"},"scenery-phet":{"sha":"5a6969fe","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"7b4a98d6","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"}}

**Comment by arouinfar** [comment] 2015-12-01 22:38
Nice observation @brroberts1231. 

This behavior is deliberate. The goal is to allow users to maximize the playspace. If the window size is decreased, the objects should follow the edge of the screen until they reach the edge of the dev boundary.

However, it looks like the laser does not behave properly when the window is resized. I'm having trouble consistently reproducing this issue in dev.45 with 10.11.1/Chrome, but this procedure will generally work:

1. Open prisms screen in wider aspect ratio, and drag the laser as far to the left as possible.
![image](https://cloud.githubusercontent.com/assets/8419308/11516565/4673a2ba-9841-11e5-8986-bebd4ae03d63.png)

2. Resize the window to be narrower. Sometimes the laser will flip instead of scoot with the edge of the screen. I've noticed that the rotation arrows move to an odd location.
![screen shot 2015-12-01 at 3 32 34 pm 2](https://cloud.githubusercontent.com/assets/8419308/11516567/48619262-9841-11e5-924d-a3a55a9097a2.png)

**Comment by samreid** [comment] 2015-12-04 06:03
Fixed above, straightforward, tests show it is fixed, no need to reassign for verification, closing.

**Closed by samreid** 2015-12-04 06:03 UTC
Labels: bug
