### ISSUE TITLE
Laser can be vertically removed from display on Prisms Screen

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#54] opened 2015-06-01 16:33 UTC
The Laser can be removed from play area on Prisms Screen. 

To reproduce:
Open sim
Select Prisms Screen
Rotate Laser such that it stands vertically
Drag Laser to the top of the screen

![screen shot 2015-06-01 at 10 28 50 am](https://cloud.githubusercontent.com/assets/5631059/7917726/88390128-0849-11e5-9414-96c80928012c.png)
![screen shot 2015-06-01 at 10 29 02 am](https://cloud.githubusercontent.com/assets/5631059/7917729/8aee4df6-0849-11e5-8d0a-9c5215b220a3.png)

**Comment by bryo5363** [comment] 2015-06-01 16:37
I could not reproduce this issue on Chrome 43 Windows 7

**Comment by arnabp** [comment] 2015-06-01 21:22
I could not reproduce this issue on Safari 8 Mac Yosemite 10.10

**Comment by bryo5363** [comment] 2015-06-02 16:44
I reproduced this issue on OSX 10.9.5 Safari 7.1 but with a different method

1) enlarge screen as wide as you can
2) open prisms
3) rotate laser to its minimum position
4) drag the laser downwards

**Comment by arouinfar** [comment] 2015-06-02 19:26
I reproduced this issue on OSX 10.9.5 in Chrome 43 using the method @orejolaphet described. I found that the laser was still retrievable if I hovered over the edge of the browser window where the laser was dragged out.
![image](https://cloud.githubusercontent.com/assets/8419308/7944916/ccf0272e-092a-11e5-8f7b-e00daeb48657.png)

**Comment by ChandrashekarBemagoni** [comment] 2015-06-12 04:59
Fixed in latest code . Assigning to @arouinfar for verification

**Comment by arouinfar** [comment] 2015-06-17 19:48
Looks good! Closing.

**Closed by arouinfar** 2015-06-17 19:48 UTC
