### ISSUE TITLE
Render white light with WebGL

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#53] opened 2015-06-01 16:22 UTC
I noticed this issue on Chrome 43.0.2357.81 m on Windows 7

When enabling the white light feature on the Prisms portion of the simulation, the performance of the simulation is slowed down tremendously.

**Comment by bryo5363** [comment] 2015-06-01 16:25
In addition to this, I noticed the simulation will run slow if many prisms are dragged into the boundary and multiple rays of light are selected. This does not need white light to be enabled

**Comment by arouinfar** [comment] 2015-06-02 19:45
I also noticed this while using OSX 10.9.5 and Chrome 43. Even with a single prism, the performance is unacceptably sluggish when using White Light.

**Comment by elisemorgan** [comment] 2015-06-05 21:13
I also noticed this while use the iPad 2 with iOS8. The entire screen freezes almost immediately.

**Comment by samreid** [comment] 2015-08-08 23:11
Let's track the "multiple rays performance issue" in #74.

**Comment by samreid** [comment] 2015-08-21 16:55
Now that we have a good WebGL implementation for solid rays, we can use this as a starting place for a WebGL implementation white light.  I will likely benefit significantly from @jonathanolson's help for blending the colors properly, but I'll start this out on my own.

**Comment by samreid** [comment] 2015-08-21 17:06
The white light renderer may be general enough to render all rays (solid ones too).  That would be interesting.

**Comment by samreid** [comment] 2015-08-21 17:16
The solid renderer looks pretty good here.  Great performance on iPad3.  We still have to work on the blending, it currently looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/9414485/fc3f6e4a-47f5-11e5-9f68-f543a485d8ac.png)

**Comment by samreid** [comment] 2015-08-21 17:27
```js
      gl.enable( gl.BLEND );
      gl.blendEquation( gl.FUNC_ADD );
      gl.blendFunc( gl.SRC_ALPHA, gl.ONE );
```
looks pretty good:
![image](https://cloud.githubusercontent.com/assets/679486/9414651/65f46b5a-47f7-11e5-8e46-47818b2a7592.png)

But now I'm remembering we designed the sim to have the rays add up to gray instead of white.  This could be harder.  

One possibility would be to gray the background slightly to accentuate the fact that the light is white, then we can continue to use this hardware optimization.  Not sure what I'd do next to turn white pixels gray--perhaps something in the vertex shader???

**Comment by samreid** [comment] 2015-08-21 17:28
Also, it looks like some of the channels are oversaturating.

**Comment by jonathanolson** [comment] 2015-08-22 01:10
> One possibility would be to gray the background slightly to accentuate the fact that the light is white

That sounds nice to me.

It would also be possible to render the "true white" lines into a framebuffer (backed by a texture), then use another fragment shader to map values to the desired appearance.

**Comment by samreid** [comment] 2015-08-24 13:19
I'll create a separate issue about asking whether we should use true white for the white light, or find a way to support gray light (against a white background).

**Comment by samreid** [comment] 2015-08-25 19:57
We're going to try gray light, @jonathanolson can you help point me in the right direction with the framebuffer texture idea?  Any examples you can point me to?  Also, why did you recommend this approach over say, a custom fragment shader?

**Comment by jonathanolson** [comment] 2015-08-25 20:09
Discussing with voice would be best, but ElectricPotentialGridWebGLNode has most of the patterns you would need.

It uses a "compute" shader to render to a framebuffer (alternating between two textures, one which is read from as a texture, and the other texture gets the output written to it). Then it uses a "display" shader to render to the main Canvas, using one of the textures as input.

You wouldn't need the floating-point texture stuff, and you wouldn't need two textures for the framebuffer (only one).

But it would be "render true white-light into texture via framebuffer", then "render data from texture into Canvas, mapping colors as needed", with two shaders.

**Comment by jonathanolson** [comment] 2015-08-25 20:19
> Also, why did you recommend this approach over say, a custom fragment shader?

It seems to me that two steps are required, if you want to first blend together light rays that overlap, and THEN map the color. If you can just change how they blend to achieve the required affect, no framebuffer is needed.

**Comment by samreid** [comment] 2015-08-26 01:55
Thanks, I'll take a look around and let you know when I am ready to continue with voice, etc.

**Comment by samreid** [comment] 2015-08-29 22:00
@jonathanolson will I be able to write my own color combination functions in WebGL?  The implementation we decided on for Java had the following form:

r, g, b values for each ray are summed independently and divided by 0.017
ray alpha values are interpreted as intensities are summed directly (no scale factor)

where rays combine (or even for single rays):
1. let max = max(r,g,b) at that point
2. let whiteLimit = 0.2;
3. let maxChannel = 1 - whiteLimit;
4. let scale = 2; // makes it white instead of cream/orange
4. compute r,g,b values according to `samples[ i ] = Util.clamp( samples[ i ] / max * scale - whiteLimit, 0, maxChannel );`
5. compute alpha = `Util.clamp( Math.sqrt( intensity ), 0, 1 );`

Full details and implementation for canvas are in bending-light/js/prisms/view/WhiteLightCanvasNode.js.  Is there a WebGL combination rule which adds r,g,b and alpha values without clamping them?  Then I could do everything in the fragment shader, right?  Or perhaps I could just downscale everything before giving it to webgl so that when it adds values together it would be unlikely to saturate, then I can rescale everything back up in the fragment shader.

It would be great if you could familiarize yourself with the desired behavior in WhiteLightCanvasNode.js and help make sure I'm pointed in the right direction.

**Comment by samreid** [comment] 2015-08-29 22:04
I'm also seeing that the blending is configured like so in WebGLBlock.js

```js
gl.enable( gl.BLEND );
gl.blendEquationSeparate( gl.FUNC_ADD, gl.FUNC_ADD );
gl.blendFuncSeparate( gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA, gl.ONE, gl.ONE_MINUS_SRC_ALPHA );
```

So it looks like I will need to configure the alpha channels to add, right?  I haven't used blendFuncSeparate before.  Should I override this somehow to handle my intensity channel?

**Comment by samreid** [comment] 2015-08-29 22:30
Here's my current go at a fragment shader.  Still not sure if I'm barking up the right tree.  I've commented out the gl.blendFuncSeparate for testing this:

```js
        // Returns the color from the vertex shader
        'void main( void ) {',
        '  float colorScale = 0.017;',
        '  float r = vColor.r*colorScale;',
        '  float g = vColor.g*colorScale;',
        '  float b = vColor.b*colorScale;',
        '  float max = r;',
        '  float scale = 2.0;',
        '  float whiteLimit = 0.2;',
        '  float maxChannel = 1.0-whiteLimit;',
        '  if (g > max) {max=g;}',
        '  if (b > max) {max=b;}',
        '  float rNew = r/max*scale-whiteLimit;',
        '  float gNew = g/max*scale-whiteLimit;',
        '  float bNew = b/max*scale-whiteLimit;',
        '  if (rNew < 0.0) {rNew = 0.0;}',
        '  if (gNew < 0.0) {gNew = 0.0;}',
        '  if (bNew < 0.0) {bNew = 0.0;}',
        '  if (rNew > maxChannel) {rNew = maxChannel;}',
        '  if (gNew > maxChannel) {gNew = maxChannel;}',
        '  if (bNew > maxChannel) {bNew = maxChannel;}',
        '  gl_FragColor = vec4(r/max*scale-whiteLimit,g/max*scale-whiteLimit,b/max*scale-whiteLimit,sqrt(vColor.a));',
        '}'
```

**Comment by samreid** [comment] 2015-08-29 22:32
oops typo in the last line, hold steady.

```js
'  gl_FragColor = vec4(rNew,gNew,bNew,sqrt(vColor.a));',
```

**Comment by samreid** [comment] 2015-08-29 22:36
The fragment shader gets called after the colors have been combined, right?

**Comment by samreid** [comment] 2015-08-30 02:55
Looks like colors are being blended *after* the fragment shader?

**Comment by samreid** [comment] 2015-08-30 03:15
Indeed, according to https://www.opengl.org/wiki/Rendering_Pipeline_Overview the blending is applied to the outputs of the fragment shader.  Not sure if/how my strategy above could work then.

**Comment by samreid** [comment] 2015-08-30 03:47
I think the next thing to try is rendering to a texture via a framebuffer.  This process looks like it will take several hours for me to understand and implement and make sure the geometry is right.  After that is set up, I can try applying my own color mapping functions in the texture render call.

**Comment by samreid** [comment] 2015-08-31 17:46
@jonathanolson suggested using standard illuminants such as described here:
http://onlinelibrary.wiley.com/store/10.1002/9781119975595.app5/asset/app5.pdf;jsessionid=2042475B31D37579880053ED67651927.f02t04?v=1&t=ie07hzfa&s=355b8e451d7aa17fd6006bdb74d77f994e19ce6e

Sampling from this table in the D65 column (for standard daylight).  We can record the wavelength (nm) values for dispersion but use the XYZ values for combination in the RGB columns webgl.  There is a lookup table to go from wavelength => xyz.  

@jonathanolson provided this reference: http://www.brucelindbloom.com/index.html?Eqn_Spect_to_XYZ.html

Here's a table for wavelength => xyz:
http://cvrl.ioo.ucl.ac.uk/cmfs.htm For example click the left icon of the "CIE 1931 2-deg, XYZ CMFs" space for a CVS of the color mapping.

**Comment by samreid** [comment] 2015-08-31 17:58
So in the texture fragment shader, we transform back from XYZ => RGB, then we must transform to be within the gamut (clamp or transform), see https://en.wikipedia.org/wiki/Gamut, then we must scale values so white goes to gray.  We can choose the alpha value to be proportional to the magnitude of the RGB vector.

**Comment by samreid** [comment] 2015-08-31 18:08
@jonathanolson suggests using the RGB values themselves to represent the intensity.  The magnitude of the RGB vector would be used as the alpha value of the ray.  RGB(0,0,0) would be invisible since it has magnitude zero.

**Comment by samreid** [comment] 2015-08-31 18:12
We will have to downscale each of the rays before they go to the WebGL add function so they don't saturate during the ADD.  However, there are only 255 discrete values for each channel, so some rays will get mapped to the same value.

**Comment by jonathanolson** [comment] 2015-08-31 18:17
D65 power spectrum curve: http://www.cie.co.at/publ/abst/datatables15_2004/sid65.txt

**Comment by jonathanolson** [comment] 2015-08-31 18:42
Prototype-like color code:
```js
var xyz = [ [ 360, 0.0001299, 0.000003917, 0.0006061 ],
            [ 365, 0.0002321, 0.000006965, 0.001086 ],
            [ 370, 0.0004149, 0.00001239, 0.001946 ],
            [ 375, 0.0007416, 0.00002202, 0.003486 ],
            [ 380, 0.001368, 0.000039, 0.006450001 ],
            [ 385, 0.002236, 0.000064, 0.01054999 ],
            [ 390, 0.004243, 0.00012, 0.02005001 ],
            [ 395, 0.00765, 0.000217, 0.03621 ],
            [ 400, 0.01431, 0.000396, 0.06785001 ],
            [ 405, 0.02319, 0.00064, 0.1102 ],
            [ 410, 0.04351, 0.00121, 0.2074 ],
            [ 415, 0.07763, 0.00218, 0.3713 ],
            [ 420, 0.13438, 0.004, 0.6456 ],
            [ 425, 0.21477, 0.0073, 1.0390501 ],
            [ 430, 0.2839, 0.0116, 1.3856 ],
            [ 435, 0.3285, 0.01684, 1.62296 ],
            [ 440, 0.34828, 0.023, 1.74706 ],
            [ 445, 0.34806, 0.0298, 1.7826 ],
            [ 450, 0.3362, 0.038, 1.77211 ],
            [ 455, 0.3187, 0.048, 1.7441 ],
            [ 460, 0.2908, 0.06, 1.6692 ],
            [ 465, 0.2511, 0.0739, 1.5281 ],
            [ 470, 0.19536, 0.09098, 1.28764 ],
            [ 475, 0.1421, 0.1126, 1.0419 ],
            [ 480, 0.09564, 0.13902, 0.8129501 ],
            [ 485, 0.05795001, 0.1693, 0.6162 ],
            [ 490, 0.03201, 0.20802, 0.46518 ],
            [ 495, 0.0147, 0.2586, 0.3533 ],
            [ 500, 0.0049, 0.323, 0.272 ],
            [ 505, 0.0024, 0.4073, 0.2123 ],
            [ 510, 0.0093, 0.503, 0.1582 ],
            [ 515, 0.0291, 0.6082, 0.1117 ],
            [ 520, 0.06327, 0.71, 0.07824999 ],
            [ 525, 0.1096, 0.7932, 0.05725001 ],
            [ 530, 0.1655, 0.862, 0.04216 ],
            [ 535, 0.2257499, 0.9148501, 0.02984 ],
            [ 540, 0.2904, 0.954, 0.0203 ],
            [ 545, 0.3597, 0.9803, 0.0134 ],
            [ 550, 0.4334499, 0.9949501, 0.008749999 ],
            [ 555, 0.5120501, 1, 0.005749999 ],
            [ 560, 0.5945, 0.995, 0.0039 ],
            [ 565, 0.6784, 0.9786, 0.002749999 ],
            [ 570, 0.7621, 0.952, 0.0021 ],
            [ 575, 0.8425, 0.9154, 0.0018 ],
            [ 580, 0.9163, 0.87, 0.001650001 ],
            [ 585, 0.9786, 0.8163, 0.0014 ],
            [ 590, 1.0263, 0.757, 0.0011 ],
            [ 595, 1.0567, 0.6949, 0.001 ],
            [ 600, 1.0622, 0.631, 0.0008 ],
            [ 605, 1.0456, 0.5668, 0.0006 ],
            [ 610, 1.0026, 0.503, 0.00034 ],
            [ 615, 0.9384, 0.4412, 0.00024 ],
            [ 620, 0.8544499, 0.381, 0.00019 ],
            [ 625, 0.7514, 0.321, 0.0001 ],
            [ 630, 0.6424, 0.265, 5E-05 ],
            [ 635, 0.5419, 0.217, 0.00003 ],
            [ 640, 0.4479, 0.175, 0.00002 ],
            [ 645, 0.3608, 0.1382, 0.00001 ],
            [ 650, 0.2835, 0.107, 0 ],
            [ 655, 0.2187, 0.0816, 0 ],
            [ 660, 0.1649, 0.061, 0 ],
            [ 665, 0.1212, 0.04458, 0 ],
            [ 670, 0.0874, 0.032, 0 ],
            [ 675, 0.0636, 0.0232, 0 ],
            [ 680, 0.04677, 0.017, 0 ],
            [ 685, 0.0329, 0.01192, 0 ],
            [ 690, 0.0227, 0.00821, 0 ],
            [ 695, 0.01584, 0.005723, 0 ],
            [ 700, 0.01135916, 0.004102, 0 ],
            [ 705, 0.008110916, 0.002929, 0 ],
            [ 710, 0.005790346, 0.002091, 0 ],
            [ 715, 0.004109457, 0.001484, 0 ],
            [ 720, 0.002899327, 0.001047, 0 ],
            [ 725, 0.00204919, 0.00074, 0 ],
            [ 730, 0.001439971, 0.00052, 0 ],
            [ 735, 0.000999949, 0.0003611, 0 ],
            [ 740, 0.000690079, 0.0002492, 0 ],
            [ 745, 0.000476021, 0.0001719, 0 ],
            [ 750, 0.000332301, 0.00012, 0 ],
            [ 755, 0.000234826, 0.0000848, 0 ],
            [ 760, 0.000166151, 0.00006, 0 ],
            [ 765, 0.000117413, 0.0000424, 0 ],
            [ 770, 8.30753E-05, 0.00003, 0 ],
            [ 775, 5.87065E-05, 0.0000212, 0 ],
            [ 780, 4.15099E-05, 0.00001499, 0 ],
            [ 785, 2.93533E-05, 0.0000106, 0 ],
            [ 790, 2.06738E-05, 7.4657E-06, 0 ],
            [ 795, 1.45598E-05, 5.2578E-06, 0 ],
            [ 800, 1.0254E-05, 3.7029E-06, 0 ],
            [ 805, 7.22146E-06, 2.6078E-06, 0 ],
            [ 810, 5.08587E-06, 1.8366E-06, 0 ],
            [ 815, 3.58165E-06, 1.2934E-06, 0 ],
            [ 820, 2.52253E-06, 9.1093E-07, 0 ],
            [ 825, 1.77651E-06, 6.4153E-07, 0 ],
            [ 830, 1.25114E-06, 4.5181E-07, 0 ] ];

// Part 2: CIE Standard Illuminant D65 relative spectral power distribution
// 300 nm - 830 nm at 5 nm intervals
var d65 = [ 0.03410, 1.66430, 3.29450, 11.76520, 20.23600, 28.64470, 37.05350, 38.50110, 39.94880, 42.43020, 44.91170, 45.77500, 46.63830, 49.36370, 52.08910, 51.03230, 49.97550, 52.31180, 54.64820, 68.70150, 82.75490, 87.12040, 91.48600, 92.45890, 93.43180, 90.05700, 86.68230, 95.77360, 104.86500, 110.93600, 117.00800, 117.41000, 117.81200, 116.33600, 114.86100, 115.39200, 115.92300, 112.36700, 108.81100, 109.08200, 109.35400, 108.57800, 107.80200, 106.29600, 104.79000, 106.23900, 107.68900, 106.04700, 104.40500, 104.22500, 104.04600, 102.02300, 100.00000, 98.16710, 96.33420, 96.06110, 95.78800, 92.23680, 88.68560, 89.34590, 90.00620, 89.80260, 89.59910, 88.64890, 87.69870, 85.49360, 83.28860, 83.49390, 83.69920, 81.86300, 80.02680, 80.12070, 80.21460, 81.24620, 82.27780, 80.28100, 78.28420, 74.00270, 69.72130, 70.66520, 71.60910, 72.97900, 74.34900, 67.97650, 61.60400, 65.74480, 69.88560, 72.48630, 75.08700, 69.33980, 63.59270, 55.00540, 46.41820, 56.61180, 66.80540, 65.09410, 63.38280, 63.84340, 64.30400, 61.87790, 59.45190, 55.70540, 51.95900, 54.69980, 57.44060, 58.87650, 60.31250 ];

function d65Lookup( wavelength ) {
  return d65[ ( wavelength - 300 ) / 5 ];
}

// max of XYZ * D65 for each channel
var maxX = 0;
var maxY = 0;
var maxZ = 0;
for ( var i = 0; i < xyz.length; i++ ) {
  var wavelength = xyz[i][0];
  maxX = Math.max( maxX, xyz[i][1] * d65Lookup( wavelength ) );
  maxY = Math.max( maxY, xyz[i][2] * d65Lookup( wavelength ) );
  maxZ = Math.max( maxZ, xyz[i][3] * d65Lookup( wavelength ) );
}

var rays = [];

// output (wavelength, X, Y, Z), normalized independently for each XYZ channel (0-1 range)
for ( var i = 0; i < xyz.length; i++ ) {
  var wavelength = xyz[i][0];
  var x = xyz[i][1] * d65Lookup( wavelength ) / maxX;
  var y = xyz[i][2] * d65Lookup( wavelength ) / maxY;
  var z = xyz[i][3] * d65Lookup( wavelength ) / maxZ;
  if ( x > 0 || y > 0 || z > 0 ) {
    console.log( wavelength, x, y, z );
    rays.push( { wavelength: wavelength, xyz: new dot.Vector3( x, y, z ) } );
  }
}

// You would want to use XYZ values in the shader which are normalized / 16 (so that they can be added together to saturate)

// Then in the display shader, before computing RGB, would need to denormalize:
// actualXYZ = vec3( x * maxX, y * maxY, z * maxZ )

console.log( 'max: ' + maxX + ', ' + maxY + ', ' + maxZ );

var xyzToRGB = new dot.Matrix3().rowMajor(
  0.4124564,  0.3575761,  0.1804375,
  0.2126729,  0.7151522,  0.0721750,
  0.0193339,  0.1191920,  0.9503041
);

var rgbSum = new dot.Vector3();

for ( var i = 0; i < rays.length; i++ ) {
  rgbSum.add( xyzToRGB.timesVector3( rays[i].xyz.componentTimes( new dot.Vector3( maxX, maxY, maxZ ) ) ) );
}
```

**Comment by samreid** [comment] 2015-09-01 00:20
The new white light canvas algorithm is working well, very simple and has a nice symmetry with the colors in the wavelength slider.  It is also very speedy, probably fast enough on iPad.  There are some corner cases to address--in this case I am seeing some dark green light where I expected light gray:

![image](https://cloud.githubusercontent.com/assets/679486/9593537/f114f336-500c-11e5-8ed4-43c8c110723b.png)

**Comment by samreid** [comment] 2015-09-01 00:38
@jonathanolson suggested another optimization:

[8/31/15, 6:07:17 PM] Jonathan Olson: Transform canvas node with model view transform
[8/31/15, 6:07:34 PM] Jonathan Olson: And change linewidth to compensate
[8/31/15, 6:07:51 PM] Jonathan Olson: Then no need for JS computed transforms on line coordinates
[8/31/15, 6:08:39 PM] Sam Reid: I’ll try it, but concerned about floating point issues putting such a large transform 1E9 or so on the canvas
[8/31/15, 6:09:00 PM] Jonathan Olson: Hmm true

**Comment by samreid** [comment] 2015-09-01 00:40
This new approach also has an aliasing issue that looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/9593749/cfefb346-500f-11e5-8291-964163d5e179.png)

**Comment by samreid** [comment] 2015-09-01 15:56
Also, when using all of the D65 rays, I'm seeing some transparency in the blue/green region:

![image](https://cloud.githubusercontent.com/assets/679486/9609206/b72c8016-508f-11e5-8c06-017ce78c2535.png)

Perhaps this is caused by using the magnitude of the xyz vector as the alpha channel?

**Comment by jonathanolson** [comment] 2015-09-01 16:40
Most likely, during discussion I thought using the RGB magnitude would be best for the alpha.

**Comment by samreid** [comment] 2015-09-01 16:51
The code was actually using XYZ.magnitude() for the alpha.  Using RGB.magnitude() instead seems to alleviate this issue somewhat: 
![image](https://cloud.githubusercontent.com/assets/679486/9610539/71e30144-5097-11e5-9bd5-df5620c1aab7.png)

**Comment by jonathanolson** [comment] 2015-09-01 16:52
Also, we could consider just using the Y channel's magnitude, as that's meant to be luminance.

**Comment by samreid** [comment] 2015-09-01 16:57
What about using the D65 entry here?  Shouldn't it contribute to the displayed intensity?

**Comment by samreid** [comment] 2015-09-01 16:59
Using D65 alone here looks pretty great (I am using _.range( 400, 700, 5 ); here):

![image](https://cloud.githubusercontent.com/assets/679486/9610704/701b6bac-5098-11e5-817d-82e5c2c7dbd1.png)

**Comment by samreid** [comment] 2015-09-01 17:00
I'll try the Y channel too.

**Comment by jonathanolson** [comment] 2015-09-01 17:00
I think the XYZ_INTENSITIES (used previously) included the D65 multiplication.

**Comment by samreid** [comment] 2015-09-01 17:01
Ah you are right.  I'll try the XYZ_INTENSITY y value.

**Comment by jonathanolson** [comment] 2015-09-01 17:01
Using D65 directly does make a lot of sense. Only seems worse if the VisibleColor darkens deep reds & violets (since we would want the "original" color to be at full intensity).

**Comment by samreid** [comment] 2015-09-01 17:04
Using 
```js
        var a = Util.clamp(
          BendingLightConstants.XYZ_INTENSITIES[ wavelength ].y * lightRay.powerFraction / 100,
          0,
          0.8
        );
```
I get a very different spectrum:

![image](https://cloud.githubusercontent.com/assets/679486/9610828/28745876-5099-11e5-9dc2-b48c5204f16a.png)

**Comment by samreid** [comment] 2015-09-01 20:25
@jonathanolson & I wrote up notes in #190 about rendering against a black background.  We should pause work on this issue until that is decided.

**Comment by samreid** [comment] 2015-09-01 21:35
The performance of the canvas version (with black background) appears qualitatively to be as fast as the webgl version--this likely means the bottleneck is somewhere other than the render phase.  Hence I think we should look into other optimizations before investigating whether WebGL is truly necessary here now that we have a nice canvas solution.

**Comment by samreid** [comment] 2015-09-01 21:35
I'll close this for now and we can reopen if we judge that the new canvas solution isn't fast enough.

**Closed by samreid** 2015-09-01 21:35 UTC
Labels: prisms-screen
