### ISSUE TITLE
Wave remains on screen after reset and screen change

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/bending-light#387] opened 2020-02-27 20:57 UTC
**Test device**
Hooke
**Operating System**
MacOS 10.15.3
**Browser**
Safari 13.0.5
**Problem description**
Appears in latest Master and published version

If the beam is set to wave in the more tools screen, the sim is reset, the screen switched away and back to the more tools screen, the screen appears at it did on reset.
**Steps to reproduce**
1. Enter the More Tools screen
2. Select the wave option
3. Reset the screen
4. Switch to a different screen
5. Switch back to More Tools
**Visuals**

![2020-02-27 13 54 02](https://user-images.githubusercontent.com/54685448/75485848-afda1f80-5968-11ea-9978-30a3baf0c2fd.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: Bending Light
URL: http://phettest.colorado.edu/bending-light/bending-light_en.html?ea&brand=phet
Version: 1.2.0-dev.0 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
Language: en-US
Window: 1424x884
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment] 2021-02-01 04:29
I'm not seeing this symptom at the moment on Mac Safari.  Leaving open for QA to double check at next RC.

**Comment by KatieWoe** [comment] 2022-02-24 19:54
I haven't reproduced on Win 11 Chrome or Mac 10.15.7 Safari 15.2. Checked on published sim. Removing ready for qa label for now. @samreid let me know if you want us to spend more time trying to track this down, or just keep an eye out.

**Comment by samreid** [comment] 2022-09-09 03:56
Closing due to the difficulty in reproducing the problem.  We can reopen if we see this in upcoming dev or RC tests.

**Closed by samreid** 2022-09-09 03:56 UTC
Labels: type:bug
